### ISSUE TITLE
plz help

### ISSUE THREAD

**Issue by yashatkare** [Rjtsahu/Bus-Tracking-Parent#2]
hi i installed the server it works but when i run locally on my mobile and change ip address in app and install it does not work a app still stuck in login page.
then i move to pythonanywhere run the server it shows admin page but it does'nt shows kid reg. and driver reg. yashatkare.pythonanywhere.com/admin and apps are still stuck in login pages

**Comment by Rjtsahu** [comment]
Can you please share me logs and API response in login.

For further discussion contact mail me on sahurjt@gmail.com

**Comment by Spandu8** [comment]
You have not deployed correct backend code in your server.

You need to deploy code from "before-restructure" branch since master has code under refactoring and development so master and other branch will not work.

// so pull code from School-Bus-Tracking project 
git pull
// switch to before-restructure
git checkout before-restructure
// then publish your code in pythonanywhere

**Comment by Rjtsahu** [comment]
You have not deployed correct backend code in your server.

You need to deploy code from "before-restructure" branch since master has code under refactoring and development so master and other branch will not work.

// so pull code from School-Bus-Tracking project
git pull
// switch to before-restructure
git checkout before-restructure
// then publish your code in pythonanywhere

**Comment by yashatkare** [comment]
ok thank u so much just tell me one thing what is exact email password of both app.
my local server showing this 192.168.43.1 - - [15/Mar/2019 00:01:16] "POST /api/v1/parent/access_token HTTP/1.1" 404 -

**Comment by Rjtsahu** [comment]
You need to register parent and driver or you can manually set password in
Parent and Deiver table in database.

Note: Password is hashed so plain password wont work, do one thing use same
hashed password as admin.

**Comment by Devamity** [comment]
I am unable to login due to lack of email id and pwd so provide me correct id and pwd please

**Comment by Rjtsahu** [comment]
@Devamity The app is not deployed any where, you need to host it yourself.

Hope this help

**Comment by Devamity** [comment]
Can u help me in doing that i domt have too much knowledge in that field

You can take your charges

**Comment by 6ixmediasa** [comment]
is the before-restructure branch still available?

**Comment by 6ixmediasa** [comment]
i only see, Master & Restructure
